### PR TITLE
Secrets of Magic Book Entry

### PR DESCRIPTION
**Pull request by billyhelms24**
Finish adding all SoM content

### CODE REVIEW

**Comment by MrVauxs** [comment]
It this going to be updated, or shall we merge this in as it is?

**Comment by billyhelms24** [comment]
I'll spend some more time on it this week. My apologies

**Comment by MrVauxs** [comment]
Reminder here again, if you don't think you can continue, we can simply merge it as is.

**Comment by billyhelms24** [comment]
Sorry worked on it a bit last week but didn't sync my changes @MrVauxs

**Pull request merged**
