### PR TITLE
lomm 60%

### PR DESCRIPTION
**Pull request by KierannS**

### CODE REVIEW

**Comment by KierannS** [comment]
it's showing literally every change i made to creatures and items as conflicts? not sure what i'm doing wrong. these files should be completely untouched no?

**Comment by MrVauxs** [comment]
> it's showing literally every change i made to creatures and items as conflicts? not sure what i'm doing wrong. these files should be completely untouched no?

first conflicts I see and it's all typos
I've been fixing conflicts in earlier PRs but these you should be able to resolve on your own.

**Comment by KierannS** [comment]
I'm still not sure what conflicts actually are, or how to fix them

**Comment by MrVauxs** [comment]
> I'm still not sure what conflicts actually are, or how to fix them

pull from `upstream/dev` to your branch and you will have git complain about the merge conflicts
once you fix them, you push the commit and it'll be fixed here

**Pull request closed without merging**
